### ISSUE TITLE
Finished match, javascript still trying to increase time

### ISSUE THREAD

**Issue by ijandric97** [marinvl/RWA_project#5]
Uncaught TypeError: Cannot read property 'innerHTML' of null

sec and min do not exist in past finished matches

**Comment by Mrkimed045** [comment]
ovo radi zato sto treba mu 5 min da skuzi da je game gotov, kad bi to smanjili na 2 min, onda bi to isto radio 2 min dok ne skuzi da je game gotov, te bi nakon 2 min, napisao game is over i stopirao js
to je rijeseno
